$schema: ['{{ _file_dir }}/_schemas/config.yml']

movies:
  - title: The Shawshank Redemption
    year: 1994
    categories: [Crime, Drama]
    rating: 9.3
  - title: The Godfather
    year: 1972
    director: Francis Ford Coppola
    categories: [Crime, Drama]
    rating: 9.2
