AllCops:
  TargetRubyVersion: '2.3'
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics:
  Enabled: false
Naming/BlockParameterName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
